CREATE TABLE post (
    id CHAR(36) DEFAULT (UUID()) PRIMARY KEY,
    title VARCHAR(300) NOT NULL,
    content TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);