CREATE TABLE users (
	user_id VARCHAR(20) PRIMARY KEY,
	username VARCHAR(50) NOT NULL,
	password CHAR(96) NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	delete_at TIMESTAMP NULL
);